name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate 3D Graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ritesh123malik
          MAX_REPOS: 10
          SETTING_JSON: |
            {
              "githubUserName": "ritesh123malik",
              "type": "normal",
              "animation": true,
              "outputFile": "profile-3d-contrib/profile-night-rainbow.svg"
            }

      - name: Commit & Push 3D Graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contribution graph [skip ci]"
          file_pattern: "profile-3d-contrib/*.svg"
          branch: main
